Rteqs/subsampling
latchbio/latch-plots-faas pull request #10
Opened 2024-09-24 17:35 UTC by rteqs

2024-10-03 17:04 UTC, maximsmol requested changes

2024-10-03 17:04 UTC, maximsmol commented on runtime/mount/subsample.py
> +                distinct on ({distinct_cols})
should this be `group by` instead? unsure

2024-10-03 17:04 UTC, maximsmol commented on runtime/mount/subsample.py
> +            # extremas
```suggestion
            # extrema
```
it's latin (singular would be `extremum`)

2024-10-03 17:04 UTC, maximsmol commented on runtime/mount/subsample.py
> +        trace_data = (
ok mostly not looking at this

2024-10-03 17:04 UTC, maximsmol commented on runtime/mount/subsample.py
> +                ($name, $generation, null)
specify column names in insert and do not add `null`s and other default values

2024-10-03 17:04 UTC, maximsmol commented on runtime/mount/subsample.py
> +                ($name, null, $last_modified_time)
specify column names in insert and do not add `null`s and other default values

2024-10-03 17:04 UTC, maximsmol commented on runtime/mount/subsample.py
> +    # convert fig to downsample config
this should be `todo`?

2024-10-03 17:04 UTC, maximsmol commented on runtime/mount/subsample.py
> +    conn: DuckDBPyConnection, key: str, df: DataFrame, config: PlotConfig, cur_gen: int
use `in_memory_{key}` as the table name to avoid conflicts

2024-10-08 23:26 UTC, rteqs commented on runtime/mount/kernel.py
> +        if config is not None and config == self.plot_configs.get(plot_id):
ok

2024-10-09 17:41 UTC, merged